# Site settings
title: Globacom
description: > # this means to ignore newlines until "baseurl:"
  We believe in building safe, valuable phone connections around the world.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://globacom.com"
# url: "http://localhost:4000"

# Contact Details
email: hello@globacom.com
phone: +41 44 505 9109
address:
  - street: 6340 Baar ZG <br>
  - country: Switzerland
facebook: globacom
twitter: globacom
instagram: globacom

# Build settings
markdown: kramdown

collections:
  products:
    output: true
